# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-26 05:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appjardin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anolectivo',
            options={},
        ),
        migrations.AlterModelOptions(
            name='estudiante',
            options={},
        ),
        migrations.AlterModelOptions(
            name='matricula',
            options={},
        ),
        migrations.AlterModelOptions(
            name='nivel',
            options={},
        ),
        migrations.AlterModelOptions(
            name='paralelo',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pension',
            options={},
        ),
        migrations.AlterModelOptions(
            name='preinscripcion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='profesor',
            options={},
        ),
        migrations.AlterModelOptions(
            name='representante',
            options={},
        ),
        migrations.AlterModelOptions(
            name='representanteestudiante',
            options={},
        ),
        migrations.AlterModelOptions(
            name='rol',
            options={},
        ),
        migrations.AlterModelOptions(
            name='secretaria',
            options={},
        ),
    ]
