# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-27 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appjardin', '0002_auto_20180927_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuser',
            name='cedula',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='authuser',
            name='direccion',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='authuser',
            name='genero',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
