# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-27 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appjardin', '0005_auto_20180927_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='preinscripcion',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
