# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-30 16:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appjardin', '0007_auto_20180927_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='nivel',
            name='cupos',
            field=models.IntegerField(default=0, verbose_name='Cupos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nivel',
            name='id_profesor',
            field=models.ForeignKey(db_column='id_profesor', default=1, on_delete=django.db.models.deletion.CASCADE, to='appjardin.Profesor', verbose_name='Profesor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nivel',
            name='paralelo',
            field=models.CharField(default='A', max_length=10, verbose_name='Paralelo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profesor',
            name='ciudad',
            field=models.CharField(default='Loja', max_length=50, verbose_name='Ciudad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profesor',
            name='direccion',
            field=models.CharField(default='direccion', max_length=50, verbose_name='Dirección'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profesor',
            name='edad',
            field=models.IntegerField(default=25, verbose_name='Edad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profesor',
            name='genero',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Otro', 'Otro')], default='masculino', max_length=10, verbose_name='Género'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profesor',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenprofesor', verbose_name='Imagen'),
        ),
        migrations.AddField(
            model_name='profesor',
            name='observacion',
            field=models.CharField(default='', max_length=500, verbose_name='Observación'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='authuser',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='last_name',
            field=models.CharField(max_length=30, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='Contraseña'),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='username',
            field=models.CharField(max_length=150, unique=True, verbose_name='Nombre de Usuario'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='id_preinscripcion',
            field=models.ForeignKey(db_column='id_preinscripcion', on_delete=django.db.models.deletion.CASCADE, to='appjardin.Preinscripcion', verbose_name='Preinscripción'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='celular',
            field=models.CharField(max_length=25, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='estado_civil',
            field=models.CharField(choices=[('Soltero', 'Soltero'), ('Casado', 'Casado'), ('Divorciado', 'Divorciado'), ('Viudo', 'Viudo')], max_length=10, verbose_name='Estado Civil'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='titulo_profesor',
            field=models.CharField(max_length=50, verbose_name='Título'),
        ),
    ]
