# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-30 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appjardin', '0008_auto_20180930_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='genero',
            field=models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Otro', 'Otro')], max_length=30, null=True),
        ),
    ]
