# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-30 17:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appjardin', '0009_auto_20180930_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='id_representante',
        ),
    ]
