# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-30 17:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appjardin', '0010_remove_estudiante_id_representante'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='id_representante',
            field=models.ForeignKey(db_column='id_representante', default=1, on_delete=django.db.models.deletion.CASCADE, to='appjardin.Representante'),
            preserve_default=False,
        ),
    ]
