# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-30 17:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appjardin', '0011_estudiante_id_representante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preinscripcion',
            name='id_estudiante',
            field=models.ForeignKey(db_column='id_estudiante', on_delete=django.db.models.deletion.CASCADE, to='appjardin.Estudiante', verbose_name='Estudiante'),
        ),
        migrations.AlterField(
            model_name='preinscripcion',
            name='id_nivel',
            field=models.ForeignKey(db_column='id_nivel', on_delete=django.db.models.deletion.CASCADE, to='appjardin.Nivel', verbose_name='Nivel'),
        ),
        migrations.AlterField(
            model_name='preinscripcion',
            name='id_representante',
            field=models.ForeignKey(db_column='id_representante', on_delete=django.db.models.deletion.CASCADE, to='appjardin.Representante', verbose_name='Representante'),
        ),
        migrations.AlterField(
            model_name='preinscripcion',
            name='id_secretaria',
            field=models.ForeignKey(db_column='id_secretaria', on_delete=django.db.models.deletion.CASCADE, to='appjardin.Secretaria', verbose_name='Secretaria'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='imagen',
            field=models.ImageField(default='', upload_to='imagenprofesor', verbose_name='Imagen'),
            preserve_default=False,
        ),
    ]
