# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-27 15:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appjardin', '0013_remove_estudiante_id_secretaria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='id_representante',
            field=models.ForeignKey(db_column='id_representante', on_delete=django.db.models.deletion.CASCADE, to='appjardin.Representante', verbose_name='Representante'),
        ),
    ]
