version: '3.1'

services:
  db:
    image: postgres
  web:
    build: .
    command: python manage.py runserver 172.20.0.3:8000
    volumes:
      - .:/mfcy
    ports:
      - "8000:8000"
    depends_on:
      - db
